"""Elementary large-genus gonality bounds for faithful A7-curves (GONALITY_LARGE_GENUS.md).
For a pencil of degree d: B(d) = max over the two cases of the genus bound
  pair case  : (d-1)^2                       (Castelnuovo-Severi, two pencils generating C(C))
  chain case : pi(t d, 2^t - 1), 3 <= t <= 1 + Omega(d)   (Segre map of a chain of conjugate pencils, Castelnuovo)
and the list of A7-signatures in the window 336 <= g <= 529 that the elementary argument does not reach."""
import itertools, sys, os
from math import comb, lcm
from fractions import Fraction as F
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from a7 import A7, order, cycle_type
from signatures_spectrum import curves


def pi(n, r):
    k, t = divmod(n - 1, r - 1)
    return (r - 1) * comb(k, 2) + k * t


def Omega(d):
    n, c, p = d, 0, 2
    while n > 1:
        while n % p == 0:
            n //= p; c += 1
        p += 1
    return c


print(" d  Omega  pair (d-1)^2   chain bounds pi(td,2^t-1), t=3..1+Omega     B(d)")
B = {}
for d in range(2, 25):
    chain = {t: pi(t * d, 2 ** t - 1) for t in range(3, 2 + Omega(d))}
    B[d] = max([(d - 1) ** 2] + list(chain.values()))
    print(f"{d:2d}  {Omega(d):4d}  {(d-1)**2:8d}      {chain}   {B[d]}")


def cost(d):
    """least delta-invariant forced by one dependent third: min C(m,2)+C(m',2), m >= m', m + m' >= d."""
    return min(comb(m, 2) + comb(mp, 2) for m in range(d + 1) for mp in range(m + 1) if m + mp >= d)


print("\nWith the dependent-third cost c(d):  pair case => g <= max((d-1)^2 - c(d), pi(3d,7))")
Bs = {}
for d in range(2, 25):
    chain = [pi(t * d, 2 ** t - 1) for t in range(3, 2 + Omega(d))]
    Bs[d] = max([(d - 1) ** 2 - cost(d), pi(3 * d, 7)] + chain)
    print(f"  d={d:2d}: c(d)={cost(d):3d}  (d-1)^2-c(d)={(d-1)**2 - cost(d):3d}  pi(3d,7)={pi(3*d,7):3d}  B*(d)={Bs[d]}")
print("B*(d) <= 335 for d <=", max(d for d in range(2, 25) if all(Bs[e] <= 335 for e in range(2, d + 1))))
B = Bs
print("\nClaim(d) for ALL genera (base g <= 335 certified) holds when B(d) <= 335:",
      [d for d in range(2, 25) if B[d] <= 335])
print("largest d with B(d) <= 335:", max(d for d in range(2, 25) if all(B[e] <= 335 for e in range(2, d + 1))))

G = list(A7)
ORD = [2, 3, 4, 5, 6, 7]
MAXIND = {o: max(7 - len(cycle_type(x)) for x in G if order(x) == o) for o in ORD}
print("\nSignatures (h = 0) with 336 <= g <= 529 passing the seven-sheeted test (and, for r = 3, generated by A7):")
for r in range(3, 7):
    for es in itertools.combinations_with_replacement(ORD, r):
        g = 1 + 1260 * (-2 + sum(1 - F(1, e) for e in es))
        if g.denominator != 1 or not (336 <= g <= 529):
            continue
        if sum(MAXIND[e] for e in es) < 12:
            continue
        if r == 3 and not any(curves(*p) for p in set(itertools.permutations(es))):
            continue
        dd = [d for d in range(20, 25) if B[d] >= g]
        print(f"   {es}  g = {int(g)}  {'rigid' if r == 3 else f'{r - 3}-dim family'};  pencils of degree {dd} not excluded")
print("(h >= 1 gives g >= 631.)")
