"""Exact checks behind 5_ACCESSORY.md sections 5.2-5.3 (the accessory threshold a(A7) = 60 of GPT's DAY-2 reference).

  1. Minimum faithful genus 136: every hyperbolic triangle signature with orders in {2,...,7} and genus < 136
     has no generating triple of A7 (exhaustive search, signatures_spectrum.curves).  Four or more branch
     points, or quotient genus >= 1, already give genus >= 211.
  2. Signatures with 136 <= g <= 325: complete list, the seven-sheeted Riemann-Hurwitz test, the linearised
     degree lattice N = |A7| / lcm(e_i), and the Castelnuovo comparison for the lattice-compatible degrees
     n = 6k <= 54 in P^5.
  3. Arithmetic of the subgroup table: [A7:H] * (lower bound for mu(H)) >= 60 for every type of index < 60
     (subgroup list: ATLAS, cited), with the Castelnuovo numbers used for A6 and PSL2(7).
  4. Sanity check: element orders of subgroups generated by random pairs (orders between 42 and 2520 that occur).
"""
import os
import sys
import itertools
import random
from fractions import Fraction as Fr
from math import comb, gcd
from functools import reduce
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from a7 import A7, generated, order, cycle_type
from signatures_spectrum import curves

lcm = lambda xs: reduce(lambda a, b: a * b // gcd(a, b), xs, 1)


def castelnuovo(n, r):
    k, t = divmod(n - 1, r - 1)
    return (r - 1) * comb(k, 2) + k * t


def genus(es, h=0):
    return 1 + 1260 * (2 * h - 2 + sum(1 - Fr(1, e) for e in es))


ORDERS = sorted({order(g) for g in A7} - {1})
assert ORDERS == [2, 3, 4, 5, 6, 7] and lcm(ORDERS) == 420
# max index (7 - #cycles) of an element of each order in the natural degree-7 action
MAXIND = {o: max(7 - len(cycle_type(g)) for g in A7 if order(g) == o) for o in ORDERS}

# 1. minimum genus
low = []
for es in itertools.combinations_with_replacement(ORDERS, 3):
    g = genus(es)
    if g > 1 and g < 136:
        low.append((es, int(g)))
for es, g in low:
    found = 0
    for perm in set(itertools.permutations(es)):
        found += len(curves(*perm))
    assert found == 0, (es, g)
print(f"1. triangle signatures with 1 < g < 136: {[es for es, _ in low]}; none is generated by A7")
assert min(g for g in (genus(es) for es in itertools.combinations_with_replacement(ORDERS, 4)) if g > 1) == 211
assert genus((2,), h=1) == 631 and genus((), h=2) == 2521 and genus((2,) * 5) == 631
print("   4+ branch points: g >= 211;  quotient genus 1: g >= 631;  quotient genus >= 2: g >= 2521")
print("   minimum faithful genus = 136, attained by (2,4,7):", len(curves(2, 4, 7)), "curves up to S7/mirror")

# 2. signatures 136..325 and the Castelnuovo contradiction
print("2. signatures with 136 <= g <= 325 (seven-sheeted test: sum of max indices >= 12):")
survivors = []
for npts in (3, 4):
    for es in itertools.combinations_with_replacement(ORDERS, npts):
        g = genus(es)
        if g.denominator != 1 or not (136 <= g <= 325):
            continue
        ok7 = sum(MAXIND[e] for e in es) >= 12
        N = 2520 // lcm(es)
        assert N % 6 == 0
        cand = [n for n in range(6, 55, 6) if n % N == 0]
        verdict = "excluded by 7-sheeted test" if not ok7 else \
            ("no lattice degree <= 54" if not cand else
             "; ".join(f"n={n}: Castelnuovo {castelnuovo(n, 5)} < g={int(g)}" for n in cand))
        if ok7:
            survivors.append(es)
            assert all(castelnuovo(n, 5) < g for n in cand)
        print(f"   {str(es):14s} g={int(g):3d}  N={N:4d}  {verdict}")
assert castelnuovo(54, 5) == 325
print("   => no faithful A7-curve has a linearised moving bundle of degree m <= 59: mu(A7) >= 60")

# 3. subgroup table (types of index < 60, ATLAS); lower bounds for mu(H) and their products
assert castelnuovo(8, 4) == 5          # A6: degree <= 8 in P^>=4 gives genus <= 5 < 10 (minimum genus of A6)
assert castelnuovo(3, 2) == 1          # PSL2(7): degree <= 3 in P^>=2 gives genus <= 1 < 3
table = {"A7": (1, 60), "A6": (7, 9), "PSL2(7)": (15, 4), "S5": (21, 3), "(A4xC3):2": (35, 2), "A5": (42, 2)}
for H, (idx, mu) in table.items():
    print(f"3. {H:10s} index {idx:2d}  mu >= {mu:2d}  product >= {idx * mu}")
    assert idx * mu >= 60
print("   index >= 60: product >= 60 trivially;  upper bound: PSL2(7) with the Klein quartic, 15 * 4 = 60")

# 4. sanity check on subgroup orders (not a proof; the subgroup list is cited from the ATLAS)
rng = random.Random(0)
seen = set()
for _ in range(3000):
    H = generated([rng.choice(A7), rng.choice(A7)])
    if 42 < len(H) < 2520:
        seen.add(len(H))
print("4. orders in (42, 2520) of 2-generated subgroups found:", sorted(seen), "(ATLAS: 60, 72, 120, 168, 360)")
print("all checks passed")
